#using this file, we will give all the configuration to spin up a selenium grid with chrome and firefox nodes. We will also give the configuration to run the test suites in parallel on the selenium grid.
version: "3"
services:
  hub:
    image: selenium/hub:4.32
    #ports:
     # - 4444:4444 # bind all host interfaces so Grid is reachable via system IP, not only localhost
    #environment:
     # - SE_BIND_HOST=false
  chrome:
    image: selenium/node-chromium:4.32
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub #with this information, chrome container will know on which IP the hub is running
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true #this is to override the default maximum sessions of 1. This will allow us to run multiple tests in parallel on the chrome container.
      - SE_NODE_MAX_SESSIONS=5 #this is to set the maximum sessions to 5. This will allow us to run 5 tests in parallel on the chrome container.
      - SE_VNC_NO_PASSWORD=1 #this is to disable the VNC password. By default, the VNC server is password protected. This will allow us to connect to the VNC server without a password.
    shm_size: '2g' #this is because, by default, the container has 64MB of shared memory, which is not enough for Chrome to run properly. Increasing the shared memory size to 2GB helps to avoid crashes and improve performance.
    #deploy:
     # replicas: 5 #this will come handy when we run tests in parallel. We can have multiple chrome containers running at the same time, which will allow us to run tests in parallel and reduce the overall execution time.
  firefox:
    image: selenium/node-firefox:4.32
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub #with this information, chrome container will know on which IP the hub is running
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true #this is to override the default maximum sessions of 1. This will allow us to run multiple tests in parallel on the chrome container.
      - SE_NODE_MAX_SESSIONS=5 #this is to set the maximum sessions to 5. This will allow us to run 5 tests in parallel on the chrome container.
    shm_size: '2g' #this is because, by default, the container has 64MB of shared memory, which is not enough for Chrome to run properly. Increasing the shared memory size to 2GB helps to avoid crashes and improve performance.
    #deploy:
     # replicas: 5 #this will come handy when we run tests in parallel. We can have multiple chrome containers running at the same time, which will allow us to run tests in parallel and reduce the overall execution time.
  vendor-portal:
    image: uk040193/selenium-docker
    depends_on:
      - hub
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub #since the hub and vendor-portal are running in the same container, we don't have to give the ip address now
      - THREAD_COUNT=3
      - TEST_SUITE=vendor-portal
    volumes:
      - C:\Users\u1127187\AutomationFrameworkDocker\reports-docker\vendor-portal:/home/selenium-docker/test-output


        #now build this by navigating to the docker compose directory
      #we will notice that the test exited immediately because the hub was not ready to take
      #up the request.

      # if we comment all the other services except selenium grid and do docker compose up -d
      # then do curl http://localhost:4444/status, we will observe that the grid is not ready

  # We will make use of utility called jq. it needs to be installed. This will transform the json output of the curl command to a more readable format.
  # using jq we can traverse the json, for example jq.value will give us the output available under value
  # we will make sure jq and curl are installed in our docker images
  # check in bellsoft image which we are using has curl and jq installed
  # we will add curl and jq installation commands in dockerFile so that our image has these

  flight-reservation:
    image: uk040193/selenium-docker
    depends_on:
      - hub
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub #since the hub and vendor-portal are running in the same container, we don't have to give the ip address now
      - THREAD_COUNT=3
      - TEST_SUITE=flight-reservation
    volumes:
      - C:\Users\u1127187\AutomationFrameworkDocker\reports-docker\flight-reservation:/home/selenium-docker/test-output



        # if we have to see container specific logs of test that ran-> docker compose logs vendor-portal

